// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c50ceb3f9af5266e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type UserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c50ceb3f9af5266e, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Response struct {
	OperationSuccess     bool     `protobuf:"varint,1,opt,name=OperationSuccess,proto3" json:"OperationSuccess,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c50ceb3f9af5266e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOperationSuccess() bool {
	if m != nil {
		return m.OperationSuccess
	}
	return false
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "profile.User")
	proto.RegisterType((*UserRequest)(nil), "profile.UserRequest")
	proto.RegisterType((*Response)(nil), "profile.Response")
}

func init() { proto.RegisterFile("proto/profile.proto", fileDescriptor_c50ceb3f9af5266e) }

var fileDescriptor_c50ceb3f9af5266e = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x8c, 0xa6, 0x4e, 0x6a, 0x69, 0xd7, 0xa2, 0xa1, 0x28, 0xe8, 0x9e, 0x24, 0x87,
	0x06, 0xeb, 0xad, 0x57, 0x0f, 0x12, 0x0f, 0x5a, 0x52, 0x3c, 0xe8, 0x2d, 0xa6, 0x63, 0x0c, 0xd4,
	0xdd, 0xb8, 0xbb, 0x29, 0x78, 0xf5, 0x15, 0x7c, 0x08, 0x1f, 0xc8, 0x57, 0xf0, 0x41, 0xa4, 0xb3,
	0x8d, 0x50, 0xed, 0x6d, 0xff, 0x7f, 0x67, 0xfe, 0xf9, 0x86, 0x81, 0xfd, 0x4a, 0x49, 0x23, 0xe3,
	0x4a, 0xc9, 0xa7, 0x72, 0x8e, 0x43, 0x52, 0xcc, 0x5f, 0xc9, 0xc1, 0x51, 0x21, 0x65, 0x31, 0xc7,
	0x38, 0xab, 0xca, 0x38, 0x13, 0x42, 0x9a, 0xcc, 0x94, 0x52, 0x68, 0x5b, 0xc6, 0x1f, 0xc0, 0xbb,
	0xd3, 0xa8, 0x58, 0x07, 0xdc, 0x64, 0x16, 0x3a, 0x27, 0xce, 0xd9, 0x6e, 0xea, 0x26, 0x33, 0xc6,
	0xc0, 0xbb, 0xc9, 0x5e, 0x30, 0x74, 0xc9, 0xa1, 0x37, 0xeb, 0xc3, 0xf6, 0xe4, 0x59, 0x0a, 0x0c,
	0xb7, 0xc8, 0xb4, 0x82, 0x85, 0xe0, 0x5f, 0xca, 0x5a, 0x18, 0xf5, 0x16, 0x7a, 0xe4, 0x37, 0x92,
	0x1f, 0x43, 0xb0, 0xcc, 0x4e, 0xf1, 0xb5, 0x46, 0x6d, 0xfe, 0x8e, 0xe0, 0xf7, 0xd0, 0x4a, 0x51,
	0x57, 0x52, 0x68, 0x64, 0x11, 0x74, 0x6f, 0x2b, 0x54, 0x84, 0x36, 0xad, 0xf3, 0x1c, 0xb5, 0xa6,
	0xca, 0x56, 0xfa, 0xcf, 0x67, 0xa7, 0x16, 0x99, 0xd0, 0x82, 0xd1, 0xde, 0xb0, 0xd9, 0x9b, 0x66,
	0xd1, 0xd7, 0xe8, 0xd3, 0x81, 0xce, 0xc4, 0xda, 0x53, 0x54, 0x8b, 0x32, 0x47, 0x76, 0x0d, 0xfe,
	0x15, 0x1a, 0xda, 0xb5, 0xbf, 0xde, 0x62, 0xf1, 0x06, 0xbd, 0x5f, 0xb7, 0xa1, 0xe2, 0x07, 0xef,
	0x5f, 0xdf, 0x1f, 0x6e, 0x97, 0x07, 0xf1, 0xe2, 0x3c, 0x2e, 0xd0, 0xd4, 0x1a, 0xd5, 0xd8, 0x89,
	0x58, 0x02, 0xed, 0x14, 0x8b, 0x52, 0x1b, 0x54, 0x14, 0xb8, 0xce, 0xb0, 0x29, 0xe9, 0x90, 0x92,
	0x7a, 0xbc, 0xbd, 0x4c, 0x52, 0xab, 0xde, 0xb1, 0x13, 0x3d, 0xee, 0xd0, 0x19, 0x2e, 0x7e, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x7f, 0x00, 0x4e, 0xc4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error)
	RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) RegisterUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	GetUser(context.Context, *UserRequest) (*Response, error)
	RegisterUser(context.Context, *User) (*Response, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) GetUser(ctx context.Context, req *UserRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedProfileServiceServer) RegisterUser(ctx context.Context, req *User) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).RegisterUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _ProfileService_GetUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _ProfileService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/profile.proto",
}
