version: '3'
services:
  profile:
    build:
      context: .
      dockerfile: ./profile/Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - "mongo"
  travel: 
    build:
      context: .
      dockerfile: ./travel/Dockerfile
    ports:
    - "8082:8082"
    depends_on:
    - "mongo"
    - "redis"
  social:
    build:
      context: .
      dockerfile: ./social/Dockerfile
    ports:
    - "8083:8083"
    depends_on:
    - "mongo"
    - "neo4j"
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    command: redis-server --requirepass iPhoneMyPh0ne!!
    logging:
      driver: "none"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=issacnitinmongod
      - MONGO_INITDB_ROOT_PASSWORD=iPhoneMyPh0ne!!
      - MONGO_ROOT_USER=issacnitinmongod
      - MONGO_ROOT_PASS=iPhoneMyPh0ne!!
      - APP_MONGO_USER=issacnitinmongod
      - APP_MONGO_PASS=iPhoneMyPh0ne!!
      - APP_MONGO_DB=glimpse
    volumes:
      - $HOME/mongod:/data/db
    logging:
      driver: "none"
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/abc
    logging:
      driver: "none"