// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	ProfileId            string   `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9f8c6d814f264b, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type NearMeResponse struct {
	ProfileArray         []*Location `protobuf:"bytes,1,rep,name=profileArray,proto3" json:"profileArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NearMeResponse) Reset()         { *m = NearMeResponse{} }
func (m *NearMeResponse) String() string { return proto.CompactTextString(m) }
func (*NearMeResponse) ProtoMessage()    {}
func (*NearMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9f8c6d814f264b, []int{1}
}

func (m *NearMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NearMeResponse.Unmarshal(m, b)
}
func (m *NearMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NearMeResponse.Marshal(b, m, deterministic)
}
func (m *NearMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NearMeResponse.Merge(m, src)
}
func (m *NearMeResponse) XXX_Size() int {
	return xxx_messageInfo_NearMeResponse.Size(m)
}
func (m *NearMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NearMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NearMeResponse proto.InternalMessageInfo

func (m *NearMeResponse) GetProfileArray() []*Location {
	if m != nil {
		return m.ProfileArray
	}
	return nil
}

type Response struct {
	OperationSuccess     bool     `protobuf:"varint,1,opt,name=OperationSuccess,proto3" json:"OperationSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d9f8c6d814f264b, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOperationSuccess() bool {
	if m != nil {
		return m.OperationSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*Location)(nil), "location.Location")
	proto.RegisterType((*NearMeResponse)(nil), "location.NearMeResponse")
	proto.RegisterType((*Response)(nil), "location.Response")
}

func init() { proto.RegisterFile("proto/location.proto", fileDescriptor_1d9f8c6d814f264b) }

var fileDescriptor_1d9f8c6d814f264b = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x16, 0x4a, 0x3a, 0x8a, 0x96, 0xd5, 0x43, 0x28, 0x45, 0x42, 0x4e, 0x21, 0x87,
	0x06, 0x2b, 0xf4, 0xd0, 0x9b, 0x37, 0x05, 0xab, 0x90, 0xa2, 0x07, 0x6f, 0xdb, 0x64, 0x0c, 0x81,
	0xb8, 0xb3, 0x6c, 0x36, 0x85, 0x5e, 0x7d, 0x05, 0x9f, 0xc9, 0x27, 0xf0, 0x15, 0x7c, 0x10, 0x71,
	0xd3, 0x24, 0x16, 0x0b, 0x1e, 0xff, 0x6f, 0xfe, 0xfc, 0xf3, 0x67, 0x16, 0xce, 0x95, 0x26, 0x43,
	0x51, 0x41, 0x89, 0x30, 0x39, 0xc9, 0xa9, 0x95, 0xdc, 0x69, 0xf4, 0x78, 0x92, 0x11, 0x65, 0x05,
	0x46, 0x42, 0xe5, 0x91, 0x90, 0x92, 0x8c, 0xc5, 0x65, 0xed, 0xf3, 0xd7, 0xe0, 0xdc, 0xed, 0x9c,
	0x7c, 0x02, 0x43, 0xa5, 0xe9, 0x25, 0x2f, 0xf0, 0x36, 0x75, 0x99, 0xc7, 0x82, 0x61, 0xdc, 0x01,
	0x3e, 0x06, 0xa7, 0x10, 0x26, 0x37, 0x55, 0x8a, 0x6e, 0xcf, 0x63, 0x01, 0x8b, 0x5b, 0xfd, 0xf3,
	0x65, 0x41, 0x32, 0xab, 0x87, 0x7d, 0x3b, 0xec, 0x80, 0x7f, 0x03, 0x27, 0xf7, 0x28, 0xf4, 0x12,
	0x63, 0x2c, 0x15, 0xc9, 0x12, 0xf9, 0x1c, 0x8e, 0x77, 0xc1, 0xd7, 0x5a, 0x8b, 0xad, 0xcb, 0xbc,
	0x7e, 0x70, 0x34, 0xe3, 0xd3, 0xf6, 0x27, 0x9a, 0x4e, 0xf1, 0x9e, 0xcf, 0x9f, 0x83, 0xd3, 0x66,
	0x84, 0x30, 0x7a, 0x50, 0xa8, 0xad, 0x6d, 0x55, 0x25, 0x09, 0x96, 0xa5, 0x2d, 0xed, 0xc4, 0x7f,
	0xf8, 0xec, 0x83, 0xc1, 0x69, 0x13, 0xb9, 0x42, 0xbd, 0xc9, 0x13, 0xe4, 0x4f, 0x30, 0xa8, 0x5b,
	0xf1, 0x03, 0x7b, 0xc7, 0x6e, 0xc7, 0xf6, 0xbb, 0xfb, 0x17, 0x6f, 0x9f, 0x5f, 0xef, 0x3d, 0xd7,
	0x3f, 0x6b, 0x4f, 0x1e, 0x6d, 0x2e, 0x23, 0x89, 0x42, 0xbf, 0xe2, 0x82, 0x85, 0xfc, 0x19, 0x46,
	0x8f, 0x2a, 0x15, 0x06, 0x97, 0xdb, 0xf6, 0xb2, 0x87, 0x36, 0xfc, 0x62, 0xff, 0x64, 0x57, 0x36,
	0x6e, 0xc1, 0xc2, 0xf5, 0xc0, 0x3e, 0xda, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x5e,
	0x9c, 0x5a, 0xf4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationServiceClient interface {
	NearMe(ctx context.Context, in *Location, opts ...grpc.CallOption) (*NearMeResponse, error)
	UpdateMyLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Response, error)
}

type locationServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocationServiceClient(cc *grpc.ClientConn) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) NearMe(ctx context.Context, in *Location, opts ...grpc.CallOption) (*NearMeResponse, error) {
	out := new(NearMeResponse)
	err := c.cc.Invoke(ctx, "/location.LocationService/NearMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) UpdateMyLocation(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/location.LocationService/UpdateMyLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
type LocationServiceServer interface {
	NearMe(context.Context, *Location) (*NearMeResponse, error)
	UpdateMyLocation(context.Context, *Location) (*Response, error)
}

// UnimplementedLocationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (*UnimplementedLocationServiceServer) NearMe(ctx context.Context, req *Location) (*NearMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NearMe not implemented")
}
func (*UnimplementedLocationServiceServer) UpdateMyLocation(ctx context.Context, req *Location) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyLocation not implemented")
}

func RegisterLocationServiceServer(s *grpc.Server, srv LocationServiceServer) {
	s.RegisterService(&_LocationService_serviceDesc, srv)
}

func _LocationService_NearMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).NearMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/NearMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).NearMe(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_UpdateMyLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).UpdateMyLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/UpdateMyLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).UpdateMyLocation(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "location.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NearMe",
			Handler:    _LocationService_NearMe_Handler,
		},
		{
			MethodName: "UpdateMyLocation",
			Handler:    _LocationService_UpdateMyLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/location.proto",
}
