name: CI

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      shell: bash
      run: |
        sshpass -p C0mputer!! ssh root@159.65.153.196
        cd /root/glife-golang
        git pull origin master
        docker-compose up --build -d
